# Service_SpeedData.yaml

apiVersion: v1
kind: Service
metadata:
  name: speed-data-service
spec:
  selector:
    app: speed-data
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP
