# Deployment_UserAuth.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-auth
  template:
    metadata:
      labels:
        app: user-auth
    spec:
      containers:
      - name: user-auth
        image: user-auth-image:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: "/app/data"
          name: user-auth-volume
#        livenessProbe:
#          httpGet:
#            path: /healthz
#            port: 5000
#          initialDelaySeconds: 10
#          periodSeconds: 5
#        readinessProbe:
#          httpGet:
#            path: /readiness
#            port: 5000
#          initialDelaySeconds: 5
#          periodSeconds: 5
      volumes:
      - name: user-auth-volume
        persistentVolumeClaim:
          claimName: user-auth-pvc
