# Service_DataProc.yaml

apiVersion: v1
kind: Service
metadata:
  name: data-processing-service
spec:
  selector:
    app: data-processing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  type: ClusterIP
